Add mac builds.

diff --git a/.github/workflows/builds.yml b/.github/workflows/builds.yml
--- a/.github/workflows/builds.yml
+++ b/.github/workflows/builds.yml
@@ -27,22 +27,23 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          # - name: mac_editor_mac_deploy
-          #   os: mac-latest
-          #   cache-name: vsekai_macos_release_x86_64.app
-          #   target: editor
-          #   tests: false
-          #   sconsflags: scu_build=yes precision=double use_volk=yes osxcross_sdk=darwin23
-          #   doc-test: false
-          #   bin: ./godot/bin/godot.macos.editor.double.x86_64
-          #   deploy-bin: ./godot/bin/godot.macos.editor.double.x86_64
-          #   proj-conv: false
-          #   artifact: true
-          #   platform: macos
-          #   deploy: true
-          #   deploy-platform: macos
-          #   export-platform: Macos
-          #   deploy-platform-target: editor
+          - name: mac_editor_mac_deploy
+            os: mac-latest
+            cache-name: vsekai_macos_release_x86_64.app
+            target: editor
+            tests: false
+            sconsflags: scu_build=yes precision=double use_volk=yes osxcross_sdk=darwin23 use_llvm=yes
+            doc-test: false
+            bin: ./godot/bin/godot.linuxbsd.editor.double.x86_64.llvm
+            deploy-bin: ./godot/bin/godot.macos.editor.double.x86_64
+            editor-bin-name: godot.macos.editor.double.x86_64
+            proj-conv: false
+            artifact: true
+            platform: linuxbsd
+            deploy: true
+            deploy-platform: macos
+            export-platform: Macos
+            deploy-platform-target: editor
 
           - name: linux_editor_win_deploy
             cache-name: linux-editor-deploy-windows-editor
@@ -114,6 +115,15 @@ jobs:
           sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
           sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
         shell: bash
+              
+      - name: Cache cctools and libtapi
+        if: ${{ matrix.platform == 'macos' }}
+        uses: actions/cache@v2
+        with:
+          path: |
+            apple-libtapi
+            cctools-port
+          key: ${{ runner.os }}-cctools-libtapi-${{ hashFiles('**/lockfiles') }}
 
       - name: Install libtapi
         if: ${{ matrix.platform == 'macos' }}
@@ -178,7 +188,7 @@ jobs:
           deploy-platform-target: ${{ matrix.deploy-platform-target }}
 
       - name: Compilation
-        if: ${{ matrix.deploy-platform == 'windows' }}
+        if: ${{ matrix.deploy-platform != 'linux' }}
         uses: ./.github/actions/godot-build
         with:
           sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
@@ -197,7 +207,7 @@ jobs:
         run: |
           mkdir -p .godot/editor .godot/imported export_${{ matrix.deploy-platform }}
           chmod +x ${{ matrix.bin }}
-          ${{ matrix.bin }} --headless --xr-mode off --export-pack ${{ matrix.export-platform }}  `pwd`/vsekai_game_${{ matrix.deploy-platform }}.pck --path . || true
+          ${{ matrix.bin }} --headless --xr-mode off --export-pack ${{ matrix.export-platform }}  `pwd`/vsekai_game_${{ matrix.deploy-platform }}.zip --path . || true
         timeout-minutes: 20
         shell: bash
 
@@ -205,15 +215,15 @@ jobs:
         if: ${{ matrix.deploy }}
         run: |
           tree -L 1
-          # Check if the .pck file exists
-          if [ ! -f ./vsekai_game_${{ matrix.deploy-platform }}.pck ]; then
-              echo "Error: vsekai_game_${{ matrix.deploy-platform }}.pck does not exist."
+          # Check if the .zip file exists
+          if [ ! -f ./vsekai_game_${{ matrix.deploy-platform }}.zip ]; then
+              echo "Error: vsekai_game_${{ matrix.deploy-platform }}.zip does not exist."
               exit 1
           fi
 
-          # Check if the path to the .pck file is correct
-          if [ ! -f `pwd`/vsekai_game_${{ matrix.deploy-platform }}.pck ]; then
-              echo "Error: The path to vsekai_game_${{ matrix.deploy-platform }}.pck is incorrect."
+          # Check if the path to the .zip file is correct
+          if [ ! -f `pwd`/vsekai_game_${{ matrix.deploy-platform }}.zip ]; then
+              echo "Error: The path to vsekai_game_${{ matrix.deploy-platform }}.zip is incorrect."
               exit 1
           fi
 
@@ -221,7 +231,7 @@ jobs:
           export TARGET=vsekai_game_${{ matrix.deploy-platform }}
           mkdir -p $TARGET
           cp -rf ${{ matrix.deploy-bin }} $TARGET/vsekai_game_${{ matrix.deploy-platform }}
-          cp -rf `pwd`/vsekai_game_${{ matrix.deploy-platform }}.pck $TARGET/vsekai_game_${{ matrix.deploy-platform }}.pck
+          cp -rf `pwd`/vsekai_game_${{ matrix.deploy-platform }}.zip $TARGET/vsekai_game_${{ matrix.deploy-platform }}.zip
           7z a -r $TARGET.zip $TARGET
         shell: bash
 
